name: Daily SVG Update

on:
  schedule:
    - cron: "0 0 * * *" # It runs every day at 00:00 UTC.
  workflow_dispatch: # Allows manual operation

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Actions' public token
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        run: node generate.js

      - name: Commit & push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.svg
          git commit -m "Bot Github: Daily SVG update" || echo "No changes"
          git push
